### PR TITLE
Spanish translation missing from basics section

### PR DESCRIPTION
**Pull request by AlanCienega**

### CODE REVIEW

**Comment by trigaten** [comment]
Thank you! Can you place that image inside of the es folder? (Check how zh-Hans does it)

**Comment by trigaten** [comment]
Could you move this to applied prompting?

**Comment by AlanCienega** [comment]
I don't understand, inside /docs/assets there is no folder called es, do you want me to create it and put the image there?

**Comment by trigaten** [comment]
> I don't understand, inside /docs/assets there is no folder called es, do you want me to create it and put the image there?

Create an `assets/` folder in [es/docusaurus-plugin-content-docs/current](https://github.com/trigaten/Learn_Prompting/tree/main/i18n/es/docusaurus-plugin-content-docs/current)

**Pull request merged**
