### PR TITLE
Badges readme

### PR DESCRIPTION
**Pull request by dr-nefardio3058**
Just some small badges that indicate extra info about the project small detail in the readme. Makes read me cleaner and prettier

Preview of the badges:

Version
License
Open Source Love png3

### CODE REVIEW

**Comment by trigaten** [comment]
The license link is broken

**Comment by dr-nefardio3058** [comment]
> The license link is broken

why? can you provide more details

**Comment by trigaten** [comment]
When clicked on, it says page cant be found: https://opensource.org/licenses/%7Blicense

**Comment by dr-nefardio3058** [comment]
> When clicked on, it says page can't be found: https://opensource.org/licenses/%7Blicense

I guess it isn't supposed to click. It's a static badge. I will take a look.

**Comment by dr-nefardio3058** [comment]
Maked the badges unclikceable and static

**Review by sorihan01 — APPROVED** [review]

**Pull request closed without merging**
