### PR TITLE
Diverse_Prompts_and_AMA

### PR DESCRIPTION
**Pull request by wesmare**
AMA Prompting updates added to Diverse Prompting Page

### CODE REVIEW

**Comment by trigaten** [comment]
Smtg is odd. Did you merge with main properly? Look how many files are changed.

**Comment by wesmare** [comment]
Shit probably not, lemme adjust and send pr again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wesmare** [comment]
whats the workflow for merging with main. I get 'There are no new commits between base branch 'main' and head branch 'Diverse_Prompts_AMA', which is the branch I used to update

**Comment by trigaten** [comment]
Your builds are failing.

**Pull request closed without merging**
