### PR TITLE
Added search component

### PR DESCRIPTION
**Pull request by eddievlagea**

### CODE REVIEW

**Comment by trigaten** [comment]
Looking awesome, please merge with main and fix the conflict.

**Comment by trigaten** [comment]
Screen Shot 2023-02-22 at 11 55 10 AM

Would it be possible to fix this problem where text is not visible?

**Comment by trigaten** [comment]
Screen Shot 2023-02-22 at 11 56 22 AM

Additionally, would it be feasible to properly show images?

**Comment by trigaten** [comment]
> For the text highlighting we're using the styles from Docusaurus, we're looking into updating it to conflict less w/ the markdown.
> 
> > Additionally, would it be feasible to properly show images?
> 
> Looking into this, the images should show

When you merge with main, the style may update. Feel free to change it. In the most recent site version, we removed the green bg on the landing page.

**Comment by trigaten** [comment]
Screen Shot 2023-02-22 at 3 31 41 PM

Could you vertically align this? The search is bumping other nav components down with it for some reason.

**Comment by trigaten** [comment]
Gotcha
1. If we want to change the green color later, how would we do so?
2. Can it work in dark mode?

**Comment by JLHasson** [comment]
> Screen Shot 2023-02-22 at 11 56 22 AM
> 
> Additionally, would it be feasible to properly show images?

We've removed the images for now. Next week we can have a version that includes images properly in the results 👌

**Pull request merged**
