### PR TITLE
French Translation of "credits.md"

### PR DESCRIPTION
**Pull request by dr-nefardio3058**
**Hi there! I have completed a French translation of the "credits.md" file and would like to offer it as a contribution to this project. This translation will allow French-speaking users to better understand and appreciate the contributions made by the influential individuals who have contributed to this project.**

Making the "credits.md" file available in French will make the project more accessible to a wider audience. This will demonstrate a commitment to diversity and inclusivity by accommodating various languages and cultures. Furthermore, this will provide an opportunity for French-speaking contributors to become involved in the project, thereby expanding its reach and impact.

_In conclusion, I believe that this French translation of "credits.md" is a valuable addition to the project, showcasing the project's commitment to inclusivity and accessibility. By providing this translation, the project will be able to connect with a broader community of contributors and users._

### CODE REVIEW

**Comment by trigaten** [comment]
Hey thank you, how much of this is AI generated? Do you speak French?

**Comment by dr-nefardio3058** [comment]
> Hey thank you, how much of this is AI generated? Do you speak French?

Some but it's understandable. I think it's a good idea to implement it because translation to french in the project is almost 0

**Comment by trigaten** [comment]
> > Hey thank you, how much of this is AI generated? Do you speak French?
> 
> Majority is AI generated. I speak some french, text it's understandable. I think it's a good idea to implement it because translation to french in the project is almost 0. Native frenchs can correct later by putting fancy language or stuff like that. But I think it's good for the first time.

Gotcha, can you ask some in the French channel to review?

**Comment by hchiam** [comment]
i'll take a look 
English reference: https://learnprompting.org/docs/credits

**Review by hchiam — CHANGES_REQUESTED** [review]
good as a first draft to get things moving, but still gotta check that the meaning/tone is preserved/consistent in certain cases

**Comment by dr-nefardio3058** [comment]
The lastest commit of this PR adresses the suggested changes. The PR is ready to merge as it has been revised and updated @trigaten

**Review by hchiam — APPROVED** [review]
LGTM! :+1:

**Comment by dr-nefardio3058** [comment]
@trigaten all suggestions have been adressed
PR ready for merge
@hchiam reviewed and approved

**Pull request merged**
