### PR TITLE
Updated Coding Assistance and Digital Marketing

### PR DESCRIPTION
**Pull request by stephenfraga**
Changes:
1. Added "Social Media Marketing" section to Digital Marketing page
2. Added "Unit Testing" section to Coding Assistance page
3. Reduced emphasis and mentions of ChatGTP since it's no longer the only AI chatbot
4. Fixed grammar
5. Clarified some areas
6. Improved some prompts
7. Improved formatting

### CODE REVIEW

**Comment by trigaten** [comment]
Please use the AIInput/ out and use the update LP embeddings. It looks like there may have been an issue with merging.

**Comment by stephenfraga** [comment]
I tried using the <AIInput> and <AIOutput> tags, but Vercel choked on them when building the preview site, so I had to revert back to manually highlighting them.

 

-Stephen

(415) 598-8715

**Comment by trigaten** [comment]
> I tried using the <AIInput> and <AIOutput> tags, but Vercel choked on them when building the preview site, so I had to revert back to manually highlighting them.
> […](#)

Perhaps run `npm I` to install everything. What is the error?

**Comment by stephenfraga** [comment]
Here you go – see attached PDF. I think it had to do with enclosing code snippets within the AIInput tag; other instances of the AIInput tag built ok.

 

-Stephen

(415) 598-8715

**Comment by stephenfraga** [comment]
Awesome, thanks for letting me know!

 

-Stephen

(415) 598-8715

**Pull request merged**
