### PR TITLE
translated side nav and intro page [arabic]

### PR DESCRIPTION
**Pull request by reda-bouzad**
Translated the side nav and the intro page into Arabic

### CODE REVIEW

**Comment by trigaten** [comment]
Thank you! Can you remove the .idea/ stuff?

**Comment by reda-bouzad** [comment]
> Thank you! Can you remove the .idea/ stuff?

done ! let me know if i can do something else

**Comment by trigaten** [comment]
Can you add the .gitignore back :)

**Comment by reda-bouzad** [comment]
I will translate the other pages when i have the time

**Comment by Smailancer** [comment]
we created telegram group contains +300 member to translate the project you can join us

**Pull request merged**
