### PR TITLE
Adds support for tooltips with details about glossary terms

### PR DESCRIPTION
**Pull request by renatonagliati**
**Tooltip:** `%%API|api%%`. Use to show a tooltip with details for a term. On the left side of the pipe is the text you want to display. On the right side is the termId.

**Glossary:** `%%RemarkAutoGlossary::list_all%%`. Use to show a list containing all terms. Important: the glossary list must be alone in a paragraph. The list is automatically sorted by ascending order based on term property of yaml file.

The details of each term need to be present in the yaml file (eg.: glossary.yml) and respecting the [following structure](https://github.com/renatonagliati/remark-auto-glossary#yaml-file-structure).

More details about the new plugin at [remark-auto-glossary](https://github.com/renatonagliati/remark-auto-glossary)

---

**Tooltip example:**

.md file:
`We make requests in an %%API|api%% to...`

After compile:
image

On mouse hover:
image

---

**Glossary example:**

.md file:
image

After compile:
image

---

Thanks

### CODE REVIEW

**Comment by trigaten** [comment]
I think there is a small problem with the plugin.
Screen Shot 2023-02-10 at 3 07 37 PM

**Comment by renatonagliati** [comment]
> I think there is a small problem with the plugin. Screen Shot 2023-02-10 at 3 07 37 PM
> 
> This should work fine:
> 
> ```
> Surprisingly, when providing few shot %%exemplars|exemplars%% in prompts, the actual answers (%%gold|gold_labels%%)
> in the exemplars are not important. As shown in the figure below, providing random
> labels in the exemplars barely hurts performance(@min2022rethinking). "Demo" is synonymous
> with exemplar in this image. %%gold|gold_labels%%
> ```
> 
> If I remove the first `%%gold|gold_labels%%`, the second works. See live problem [here](https://learn-prompting-git-fork-renatonagliati-feature-d88c5b-trigaten.vercel.app/docs/intermediate/whats_in_a_prompt#ground-truth-matters-little)

@trigaten, this problem was fixed. Please rerun ```npm install``` to get the last version (0.2.0) from ```remark-auto-glossary```.
If the problem persist, please clear the npm cache.

Thanks

**Comment by trigaten** [comment]
Did you push your changes? I am unable to see the fix even after clearing cache+rming ndde modules.

**Comment by renatonagliati** [comment]
Yes @trigaten , I pushed the commits yesterday. Please, could you uninstall the remark-auto-glossary plugin and then reinstall it?
Also it's necessary to do any change on the md file to trigger a recompile process of the corresponding page.

If the problem persists, let me know please.

Thanks

Pushed commits:
https://github.com/renatonagliati/remark-auto-glossary/commits/main

**Comment by trigaten** [comment]
I am still having the same problem. Also, can you resolve the merge conflict?

**Comment by trigaten** [comment]
TYSM!

**Pull request merged**
