### PR TITLE
Ukrainian localization package and updated configuration for Crowdin integration

### PR DESCRIPTION
**Pull request by Andrulko**
Hi there,

This PR contains some enhancements for Crowdin sync that you can apply to this project:
https://crowdin.com/project/learnprompting

docusaurus.config.js is tuned to support Ukrainian

Finally, I'm attaching a fully reviewed localization package for Ukrainian made by Summer Translation School (ЛШП) based in Kyiv, Ukraine. Looking forward to seeing them live!

The revised TM would be also shared with your Crowdin project, so only actual translations would exist in your Crowdin project for Ukrainian.

### CODE REVIEW

**Comment by Andrulko** [comment]
I decided to create a new PR instead of #862 

Image URLs should be fixed 🙌 Hope this build would be successful

**Comment by trigaten** [comment]
Thank you!

There are still a few paths missing
```
Module not found: Error: Can't resolve '../../static/img/rocket.png' in '/vercel/path0/i18n/uk/docusaurus-plugin-content-docs/current/image_prompting'
--
18:51:02.508 | Module not found: Error: Can't resolve '../../static/img/computer.png' in '/vercel/path0/i18n/uk/docusaurus-plugin-content-docs/current/image_prompting'
18:51:02.508 | Module not found: Error: Can't resolve '../../static/img/astronaut.png' in '/vercel/path0/i18n/uk/docusaurus-plugin-content-docs/current/image_prompting'
```

**Comment by Andrulko** [comment]
> Thank you!
> 
> There are still a few paths missing
> 
> ```
> Module not found: Error: Can't resolve '../../static/img/rocket.png' in '/vercel/path0/i18n/uk/docusaurus-plugin-content-docs/current/image_prompting'
> --
> 18:51:02.508 | Module not found: Error: Can't resolve '../../static/img/computer.png' in '/vercel/path0/i18n/uk/docusaurus-plugin-content-docs/current/image_prompting'
> 18:51:02.508 | Module not found: Error: Can't resolve '../../static/img/astronaut.png' in '/vercel/path0/i18n/uk/docusaurus-plugin-content-docs/current/image_prompting'
> ```

@trigaten sorry, I thought everything got fixed. These `..` are also used in English source:
https://github.com/trigaten/Learn_Prompting/blob/main/docs/image_prompting/intro.md

**Comment by Andrulko** [comment]
@trigaten done!

**Pull request merged**
