### PR TITLE
PT Translation: basics/world.md

### PR DESCRIPTION
**Pull request by FabianoLothor**
Add the Portuguese translation for the basics/world.md file.

### CODE REVIEW

**Comment by dr-nefardio3058** [comment]
So far, so good 👍

**Comment by trigaten** [comment]
Is this ready for review?

**Comment by FabianoLothor** [comment]
> Is this ready for review?

@trigaten it isn't, I'm without time to collaborate with the project.

My son did born a few weeks ago and I'm focused on him right now.

Hope to be able to contribute with the project in the nearly future.

**Comment by trigaten** [comment]
Good luck with your son :)

Closing for now.

**Pull request closed without merging**
