### PR TITLE
Add prompting products

### PR DESCRIPTION
**Pull request by fabiochiusano**
- add products to already existing product categories
- add products to new categories: Content Writing, Data Analysis, Sales and Marketing, Music, Video, Web Design
- all added products have only the product name and its URL. Do you think that a one-line description of each product should be added?

### CODE REVIEW

**Comment by trigaten** [comment]
If you already have the list of short descriptions, sure. Otherwise, no worries.

**Comment by fabiochiusano** [comment]
Yes I have it, I'll update the PR

**Comment by fabiochiusano** [comment]
I added the product descriptions (which are almost always the product taglines from their websites). It's ready for review

**Comment by trigaten** [comment]
This is awesome. TYSM.

**Pull request merged**
