### PR TITLE
German Translation of Basics

### PR DESCRIPTION
**Pull request by jesseangelis**
Hi, I translated the Basics into German I current.json, and _category_.json. I don't know if that is correct because I don't have any experience with docusaurus. Is there something that I am missing?

### CODE REVIEW

**Comment by jesseangelis** [comment]
@trigaten any idea why the vercel deployment fails?

**Comment by jesseangelis** [comment]
It worked before I changed [docusaurus.config.js](https://github.com/trigaten/Learn_Prompting/pull/723/commits/d3f1d23bc48234a7be714362daddc1942f9355b2)

**Comment by trigaten** [comment]
Could you sign the CLA?

**Comment by jesseangelis** [comment]
@trigaten done

**Pull request merged**
