### PR TITLE
Add Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by igorverse**

### CODE REVIEW

**Comment by FabianoLothor** [comment]
Hey @igorverse I did open recently a PR to include the initial files for the Portuguese translation: #349 and it was merged today.

That's why your PR is with conflicts.

I did also try to include a fallback from pt-BR to pt here: https://github.com/trigaten/Learn_Prompting/pull/349/commits/7a9474a294a3df7c6aba5df4a03a62b240c2e2d7

But the pipeline has failed, so, I'm not sure if `docusaurus` accepts this kind of configuration, I wasn't able to find anything helpful in their docs.

**Comment by igorverse** [comment]
I've added 

> Hey @igorverse I did open recently a PR to include the initial files for the Portuguese translation: #349 and it was merged today.
> 
> That's why your PR is with conflicts.
> 
> I did also try to include a fallback from pt-BR to pt here: [7a9474a](https://github.com/trigaten/Learn_Prompting/commit/7a9474a294a3df7c6aba5df4a03a62b240c2e2d7)
> 
> But the pipeline has failed, so, I'm not sure if `docusaurus` accepts this kind of configuration, I wasn't able to find anything helpful in their docs.

Are you working on a Brazilian Portuguese or European Portuguese translation?

**Comment by FabianoLothor** [comment]
> > Hey @igorverse I did open recently a PR to include the initial files for the Portuguese translation: #349 and it was merged today.
> > That's why your PR is with conflicts.
> > I did also try to include a fallback from pt-BR to pt here: [7a9474a](https://github.com/trigaten/Learn_Prompting/commit/7a9474a294a3df7c6aba5df4a03a62b240c2e2d7)
> > But the pipeline has failed, so, I'm not sure if `docusaurus` accepts this kind of configuration, I wasn't able to find anything helpful in their docs.
> 
> Are you working on a Brazilian Portuguese or European Portuguese translation?

Common Portuguese for now, since we barely started the Portuguese version, I don't think we need to maintain two or more Portuguese variations for now.

I'm located in Brazil, so you can assume that I'm working on a pt-BR version.

The `intro.md` file is already deployed.

image

image

**Comment by igorverse** [comment]
> Reference in new issue

Thinking about the growth and popularity, I think we should adopt Brazilian Portuguese first. And about your translation, I think we shouldn't translate the **prompt** term because it can act as a buzzword. So, In my opinion, it should be "Engenharia de Prompt". What do you think?

**Comment by igorverse** [comment]
image

And, like you can see, I had some Artistic freedom... I think it can works to increase our interaction with the readers.

**Comment by FabianoLothor** [comment]
> > Reference in new issue
> 
> Thinking about the growth and popularity, I think we should adopt Brazilian Portuguese first. And about your translation, I think we shouldn't translate the **prompt** term because it can act as a buzzword. So, In my opinion, it should be "Engenharia de Prompt". What do you think?

It's a tricky decision. Because imagine a person that doesn't understand a single work in English.

Personally I prefer to adapt the words as much as possible and of course, mention the correspondent word in the other language.

Like "Hoje falaremos sobre engenharia de comando (EC, ou prompt engineering no termo em inglês)", something like that.

But yeah, it's just a personal thought, you can of course open a PR with the changes to adapt that.

**Comment by FabianoLothor** [comment]
But again, any contribution is welcome, I'm not here to control that, but establish the boundaries of what translate and what not, it's an interesting topic.

Perhaps an issue with this kind of thought to hear the opinion of the others, would be a nice step.

**Comment by FabianoLothor** [comment]
My thought is the following:

Take AI (artificial intelligence) for example, certainly it's a strong buzzword, but why should we translate artificial intelligence to inteligência artificial and why should we leave engineering prompt as engenharia de prompt instead of engenharia de comando or even engineering prompt (without any translation)?

This is the kind of decision isn't a no-brain decision for me, that's why I prefer to translate as much as possible, some terms are hard to translate, a few of them are quite impossible and we need to accept that, but personally I would choose engenharia de comando or engineering prompt (without translation), partial translation of the term would be a bad decision for me.

Anyways, food for thought.

**Comment by igorverse** [comment]
> My thought is the following:
> 
> Take AI (artificial intelligence) for example, certainly it's a strong buzzword, but why should we translate artificial intelligence to inteligência artificial and why should we leave engineering prompt as engenharia de prompt instead of engenharia de comando or even engineering prompt (without any translation)?
> 
> This is the kind of decision isn't a no-brain decision for me, that's why I prefer to translate as much as possible, some terms are hard to translate, a few of them are quite impossible and we need to accept that, but personally I would choose engenharia de comando or engineering prompt (without translation), partial translation of the term would be a bad decision for me.
> 
> Anyways, food for thought.

Both "prompt engineering" and "engineering prompt" are technical terms used in software development and engineering, and their translations to Portuguese depend on the specific context in which they are being used.

However, "engenharia de prompt" is a more accurate translation for "prompt engineering" because "prompt" in this context refers to a specific type of interface or tool used in software development that displays a command line or text prompt for the user to input commands or responses. "Prompt" is commonly used in this sense in English, and "de prompt" is a common way to translate it to Portuguese.

On the other hand, "engenharia de comando" may be a valid translation for "engineering prompt" in some contexts, as "prompt" can also refer to a prompt or request for action or input. However, this translation may not convey the same specific meaning as "engenharia de prompt" and could potentially cause confusion or ambiguity for Portuguese speakers.

Ultimately, the choice of translation depends on the specific context and meaning of the term in question. In the case of "prompt engineering," "engenharia de prompt" is likely the most accurate and clear translation for the term.

**Comment by igorverse** [comment]
> > My thought is the following:
> > Take AI (artificial intelligence) for example, certainly it's a strong buzzword, but why should we translate artificial intelligence to inteligência artificial and why should we leave engineering prompt as engenharia de prompt instead of engenharia de comando or even engineering prompt (without any translation)?
> > This is the kind of decision isn't a no-brain decision for me, that's why I prefer to translate as much as possible, some terms are hard to translate, a few of them are quite impossible and we need to accept that, but personally I would choose engenharia de comando or engineering prompt (without translation), partial translation of the term would be a bad decision for me.
> > Anyways, food for thought.
> 
> Both "prompt engineering" and "engineering prompt" are technical terms used in software development and engineering, and their translations to Portuguese depend on the specific context in which they are being used.
> 
> However, "engenharia de prompt" is a more accurate translation for "prompt engineering" because "prompt" in this context refers to a specific type of interface or tool used in software development that displays a command line or text prompt for the user to input commands or responses. "Prompt" is commonly used in this sense in English, and "de prompt" is a common way to translate it to Portuguese.
> 
> On the other hand, "engenharia de comando" may be a valid translation for "engineering prompt" in some contexts, as "prompt" can also refer to a prompt or request for action or input. However, this translation may not convey the same specific meaning as "engenharia de prompt" and could potentially cause confusion or ambiguity for Portuguese speakers.
> 
> Ultimately, the choice of translation depends on the specific context and meaning of the term in question. In the case of "prompt engineering," "engenharia de prompt" is likely the most accurate and clear translation for the term.

It was a ChatGTP answer =)

**Comment by FabianoLothor** [comment]
haha, nice, that's a good way to decide what translate or not

It may be not optimal... But ask Chat-GPT for the right way to translate something would be clear and straight forward as a "translation rule" and "no-brain decision".

**Comment by trigaten** [comment]
@FabianoLothor @igorverse Love the dialogue here. Feel free to chat in the Discord translation channel for Portuguese: https://discord.gg/SddWh2Cs

**Comment by FabianoLothor** [comment]
You convinced me @igorverse, after finish `basics/intro.md` I'll update `intro.md` with your suggestion.

Thank you my friend.

**Comment by FabianoLothor** [comment]
> @FabianoLothor @igorverse Love the dialogue here. Feel free to chat in the Discord translation channel for Portuguese: https://discord.gg/SddWh2Cs

Good call @trigaten, I'll join the discord server, thank you!

**Pull request closed without merging**
